module.exports = function(router) {
  var institutionData =       {
    "success": true,
    "payload": [{
        "id": 12,
        "userNo": "012",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test4",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 13,
        "userNo": "013",
        "password": "SHA-1$1000$NcSSZziB$8ef3790303e9e59e88d172667c57821c9fa8f674",
        "name": "test5",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": "2019-01-29 20:03:57",
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 84994,
        "userNo": "admin",
        "password": "SHA-1$1000$1HupzdMg$37f4bd1ffcce092484efb414fd9e6b2752df6e16",
        "name": "admin",
        "sex": null,
        "status": null,
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": null,
        "inPosDt": null,
        "belongOrgNum": "000000",
        "belongOrg": "全行",
        "belongDeptNum": null,
        "belong_dept": null,
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": null,
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 2,
        "orgNo": "000000"
    }, {
        "id": 1,
        "userNo": "001",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "admin",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": "421222222222222222",
        "phone": "15927041111",
        "email": null,
        "birthDt": "2018-10-15",
        "inPosDt": "2018-10-17 20:32:31",
        "belongOrgNum": "000000",
        "belongOrg": "总行",
        "belongDeptNum": "D01",
        "belong_dept": "1",
        "cont_addr": null,
        "leavePosDt": "2018-10-11 20:32:27",
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": "887",
        "updatedDt": "2018-11-27 10:01:21",
        "createdDt": "2018-10-17 20:30:48",
        "orgId": 2,
        "orgNo": "000000"
    }, {
        "id": 9,
        "userNo": "009",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test1",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 10,
        "userNo": "010",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test2",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 7,
        "userNo": "007",
        "password": "SHA-1$1000$q69HmYqk$e831dffbe49ada87a842fba5273616046ddf11d4",
        "name": "admin3",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": "123456",
        "phone": "15927041111",
        "email": null,
        "birthDt": "2018-10-15",
        "inPosDt": "2018-10-17 20:32:31",
        "belongOrgNum": "000000",
        "belongOrg": "总行",
        "belongDeptNum": "D01",
        "belong_dept": "1",
        "cont_addr": null,
        "leavePosDt": "2018-10-11 20:32:27",
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": "887",
        "updatedDt": "2018-11-27 10:01:21",
        "createdDt": "2018-10-17 20:30:48",
        "orgId": 2,
        "orgNo": "000000"
    }, {
        "id": 15,
        "userNo": "015",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test7",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 16,
        "userNo": "016",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test8",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 17,
        "userNo": "017",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test9",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 18,
        "userNo": "018",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test10",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 19,
        "userNo": "019",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test11",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 20,
        "userNo": "020",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test12",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 3,
        "orgNo": "000000"
    }, {
        "id": 21,
        "userNo": "021",
        "password": "SHA-1$1000$LzvYyGfS$a83f2a7dc6eea77a8f3556f7c0506cedf7ce0cf3",
        "name": "test13",
        "sex": "1",
        "status": "1",
        "emplyPos": null,
        "emplyPost": null,
        "superEmplyNum": null,
        "idNumber": null,
        "phone": null,
        "email": null,
        "birthDt": "2019-01-15",
        "inPosDt": null,
        "belongOrgNum": "010101",
        "belongOrg": "测试机构",
        "belongDeptNum": "D01",
        "belong_dept": "3",
        "cont_addr": null,
        "leavePosDt": null,
        "enabledFlag": null,
        "updatedBy": "1",
        "createdBy": null,
        "updatedDt": null,
        "createdDt": null,
        "orgId": 9999,
        "orgNo": "000000"
    }]
  }
  router.get('/mock/crm-jj/api/user/getUserByInstitutionNo', (req, res, next) => {
    res.json(
      institutionData
    )
  })


  router.get('/mock/crm-jj/api/auth/institution/v2/searchUserByOrgNo', (req, res, next) => {
    res.json(institutionData)
  })
  router.get('/mock/crm-jj/api/auth/institution/findInstitutionTreeByUserNo2', function (req, res, next) {
    res.json(
      {
        "success":true,
        "payload":{
          "id":2,
          "orgNo":"000000",
          "coreNo":null,
          "name":"全行",
          "shname":"全行",
          "belongBrch":null,
          "superOrgNo":"*",
          "level":"0",
          "isLeafOrg":null,
          "status":"0",
          "isEnterAcctOrg":"0",
          "paySysBankNo":" ",
          "setupDt":null,
          "address":null,
          "tel":null,
          "distAreaCd":null,
          "enabledFlag":"0",
          "createdDt":"2018-09-19 00:37:15",
          "updatedDt":"2018-10-10 22:29:33",
          "createdById":"2",
          "updateById":"2",
          "children":[
            {
              "id":3157,
              "orgNo":"01001",
              "coreNo":"01000",
              "name":"test1",
              "shname":"测试机构1",
              "belongBrch":null,
              "superOrgNo":"000000",
              "level":null,
              "isLeafOrg":null,
              "status":null,
              "isEnterAcctOrg":null,
              "paySysBankNo":null,
              "setupDt":null,
              "address":null,
              "tel":null,
              "distAreaCd":null,
              "enabledFlag":null,
              "createdDt":null,
              "updatedDt":null,
              "createdById":null,
              "updateById":null,
              "children":[
                {
                  "id":3176,
                  "orgNo":"010016",
                  "coreNo":"01000",
                  "name":"test16",
                  "shname":"测试机构16",
                  "belongBrch":null,
                  "superOrgNo":"000000",
                  "level":null,
                  "isLeafOrg":"1",
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                  ],
                  "users":null
                },
                {
                  "id":3159,
                  "orgNo":"01003",
                  "coreNo":"01000",
                  "name":"test3",
                  "shname":"测试机构3",
                  "belongBrch":null,
                  "superOrgNo":"01001",
                  "level":null,
                  "isLeafOrg":null,
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                    {
                      "id":3167,
                      "orgNo":"01007",
                      "coreNo":"01000",
                      "name":"test7",
                      "shname":"测试机构7",
                      "belongBrch":null,
                      "superOrgNo":"01003",
                      "level":null,
                      "isLeafOrg":null,
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    },
                    {
                      "id":3168,
                      "orgNo":"01008",
                      "coreNo":"01000",
                      "name":"test8",
                      "shname":"测试机构8",
                      "belongBrch":null,
                      "superOrgNo":"01003",
                      "level":null,
                      "isLeafOrg":null,
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    }],
                  "users":null
                },
                {
                  "id":3160,
                  "orgNo":"01004",
                  "coreNo":"01000",
                  "name":"test4",
                  "shname":"测试机构4",
                  "belongBrch":null,
                  "superOrgNo":"01001",
                  "level":null,
                  "isLeafOrg":null,
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                    {
                      "id":3169,
                      "orgNo":"01009",
                      "coreNo":"01000",
                      "name":"test9",
                      "shname":"测试机构9",
                      "belongBrch":null,
                      "superOrgNo":"01004",
                      "level":null,
                      "isLeafOrg":null,
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    },
                    {
                      "id":3170,
                      "orgNo":"01010",
                      "coreNo":"01000",
                      "name":"test10",
                      "shname":"测试机构10",
                      "belongBrch":null,
                      "superOrgNo":"01004",
                      "level":null,
                      "isLeafOrg":null,
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    }],
                  "users":null
                }],
              "users":null
            },
            {
              "id":3158,
              "orgNo":"01002",
              "coreNo":"01000",
              "name":"test2",
              "shname":"测试机构2",
              "belongBrch":null,
              "superOrgNo":"000000",
              "level":null,
              "isLeafOrg":null,
              "status":null,
              "isEnterAcctOrg":null,
              "paySysBankNo":null,
              "setupDt":null,
              "address":null,
              "tel":null,
              "distAreaCd":null,
              "enabledFlag":null,
              "createdDt":null,
              "updatedDt":null,
              "createdById":null,
              "updateById":null,
              "children":[
                {
                  "id":3161,
                  "orgNo":"01005",
                  "coreNo":"01000",
                  "name":"test5",
                  "shname":"测试机构5",
                  "belongBrch":null,
                  "superOrgNo":"01002",
                  "level":null,
                  "isLeafOrg":null,
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                    {
                      "id":3171,
                      "orgNo":"010011",
                      "coreNo":"01000",
                      "name":"test11",
                      "shname":"测试机构11",
                      "belongBrch":null,
                      "superOrgNo":"000000",
                      "level":null,
                      "isLeafOrg":"1",
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    },
                    {
                      "id":3172,
                      "orgNo":"010012",
                      "coreNo":"01000",
                      "name":"test12",
                      "shname":"测试机构12",
                      "belongBrch":null,
                      "superOrgNo":"000000",
                      "level":null,
                      "isLeafOrg":"1",
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    }],
                  "users":null
                },
                {
                  "id":3162,
                  "orgNo":"01006",
                  "coreNo":"01000",
                  "name":"test6",
                  "shname":"测试机构6",
                  "belongBrch":null,
                  "superOrgNo":"01002",
                  "level":null,
                  "isLeafOrg":null,
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                    {
                      "id":3173,
                      "orgNo":"010013",
                      "coreNo":"01000",
                      "name":"test13",
                      "shname":"测试机构13",
                      "belongBrch":null,
                      "superOrgNo":"000000",
                      "level":null,
                      "isLeafOrg":"1",
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    },
                    {
                      "id":3174,
                      "orgNo":"010014",
                      "coreNo":"01000",
                      "name":"test14",
                      "shname":"测试机构14",
                      "belongBrch":null,
                      "superOrgNo":"000000",
                      "level":null,
                      "isLeafOrg":"1",
                      "status":null,
                      "isEnterAcctOrg":null,
                      "paySysBankNo":null,
                      "setupDt":null,
                      "address":null,
                      "tel":null,
                      "distAreaCd":null,
                      "enabledFlag":null,
                      "createdDt":null,
                      "updatedDt":null,
                      "createdById":null,
                      "updateById":null,
                      "children":[
                      ],
                      "users":null
                    }],
                  "users":null
                }],
              "users":null
            },
            {
              "id":8888,
              "orgNo":"888888",
              "coreNo":"01000",
              "name":"test8888",
              "shname":"88测试机构",
              "belongBrch":null,
              "superOrgNo":"000000",
              "level":null,
              "isLeafOrg":null,
              "status":null,
              "isEnterAcctOrg":null,
              "paySysBankNo":null,
              "setupDt":null,
              "address":null,
              "tel":null,
              "distAreaCd":null,
              "enabledFlag":null,
              "createdDt":null,
              "updatedDt":null,
              "createdById":null,
              "updateById":null,
              "children":[
              ],
              "users":null
            },
            {
              "id":3156,
              "orgNo":"01000",
              "coreNo":"01000",
              "name":"testiiiii",
              "shname":"测试机构",
              "belongBrch":null,
              "superOrgNo":"000000",
              "level":null,
              "isLeafOrg":null,
              "status":null,
              "isEnterAcctOrg":null,
              "paySysBankNo":null,
              "setupDt":null,
              "address":null,
              "tel":null,
              "distAreaCd":null,
              "enabledFlag":null,
              "createdDt":null,
              "updatedDt":null,
              "createdById":null,
              "updateById":null,
              "children":[
                {
                  "id":1,
                  "orgNo":"010100",
                  "coreNo":"010100",
                  "name":"cardCenter",
                  "shname":"信用卡中心",
                  "belongBrch":null,
                  "superOrgNo":"01000",
                  "level":null,
                  "isLeafOrg":"1",
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                  ],
                  "users":null
                },
                {
                  "id":3,
                  "orgNo":"010101",
                  "coreNo":"010101",
                  "name":"测试机构",
                  "shname":"测试机构",
                  "belongBrch":null,
                  "superOrgNo":"01000",
                  "level":null,
                  "isLeafOrg":"1",
                  "status":null,
                  "isEnterAcctOrg":null,
                  "paySysBankNo":null,
                  "setupDt":null,
                  "address":null,
                  "tel":null,
                  "distAreaCd":null,
                  "enabledFlag":null,
                  "createdDt":null,
                  "updatedDt":null,
                  "createdById":null,
                  "updateById":null,
                  "children":[
                  ],
                  "users":null
                }],
              "users":null
            }],
          "users":null
        }
      }
    )
  })
  router.post('/mock/crm-jj/api/message/detail', function (req, res, next) {
  })
}


